package github.tornaco.permission.compiler.common;

/**
 * Created by Nick@NewStand.org on 2017/4/13 10:25
 * E-Mail: NewStand@163.com
 * All right reserved.
 */

public class SettingsProvider {
    public static final String FILE_COMMENT = "This file was auto generated by AdapterCompiler. Do NOT modify~";
}
